services:
  postgres:
    image: postgres:11.10
    container_name: wakarimi-postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - ./script:/tmp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wakarimi 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
